/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_qtone_yzt_util_LameUtil */

#ifndef _Included_cn_qtone_yzt_util_LameUtil
#define _Included_cn_qtone_yzt_util_LameUtil
#ifdef __cplusplus
extern "C" {
#endif

void Java_cn_qtone_yzt_util_LameUtil_initEncoder(JNIEnv *, jobject, jint, jint, jint, jint, jint);

void Java_cn_qtone_yzt_util_LameUtil_destroyEncoder(
		JNIEnv *, jobject); 
		
void Java_cn_qtone_yzt_util_LameUtil_encodeFile(JNIEnv *,
		jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
